### ISSUE TITLE
ImportError: cannot import name environment_specific

### ISSUE THREAD

**Issue by atomlab** [pinterest/mysql_utils#4]
```
/mysql_utils# ./check_mysql_replication.py 
Traceback (most recent call last):
  File "./check_mysql_replication.py", line 4, in <module>
    from lib import host_utils
  File "/root/mysql_utils/lib/host_utils.py", line 12, in <module>
    import mysql_lib
  File "/root/mysql_utils/lib/mysql_lib.py", line 13, in <module>
    from lib import environment_specific
ImportError: cannot import name environment_specific
```
I think that in lib/ should be environment_specific.py? Right?
```
mysql_utils# ls lib/ -1
backup.py
host_utils.py
host_utils.pyc
__init__.py
__init__.pyc
mysql_connect.py
mysql_connect.pyc
mysql_lib.py
mysql_lib.pyc
timeout.py
```

**Comment by rwultsch** [comment]
The contents of this file are all environment specifics. Keys, company specific uses logger, zk servers, mappings of classic to vpc security groups,  etc...

I can create a stub for it, but everything in the file would need to be redacted.
